### ISSUE TITLE
FURY installation conflict

### ISSUE THREAD

**Issue by aryanxk02** [fury-gl/fury#395] opened 2021-03-20 12:09 UTC
Installing fury from python 3.6.8 32-bit interpreter throws this error while installing fury.

PS C:\Users\Aryan\Desktop\fury-test> pip install fury
Collecting fury
  Using cached fury-0.7.0-py3-none-any.whl (294 kB)
  Downloading fury-0.6.1-py3-none-any.whl (282 kB)
     |████████████████████████████████| 282 kB 131 kB/s 
  Downloading fury-0.6.0-py3-none-any.whl (272 kB)
     |████████████████████████████████| 272 kB 139 kB/s 
  Downloading fury-0.5.1-py3-none-any.whl (245 kB)
     |████████████████████████████████| 245 kB 156 kB/s 
  Downloading fury-0.5.0-py3-none-any.whl (177 kB)
     |████████████████████████████████| 177 kB 226 kB/s 
  Downloading fury-0.4.0-py3-none-any.whl (150 kB)
     |████████████████████████████████| 150 kB 128 kB/s 
  Downloading fury-0.3.0-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 100 kB/s 
  Downloading fury-0.2.0-py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 163 kB/s 
  Downloading fury-0.1.4-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 94 kB/s 
  Downloading fury-0.1.3-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 242 kB/s 
  Downloading fury-0.1.2-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 242 kB/s 
Collecting scipy>=0.9
  Downloading scipy-1.5.4-cp36-cp36m-win32.whl (28.3 MB)
     |████████████████████████████████| 28.3 MB 328 kB/s 
Requirement already satisfied: numpy>=1.7.1 in c:\users\aryan\appdata\local\programs\python\python36-32\lib\site-packages (from fury) (1.19.5)
Collecting fury
  Downloading fury-0.1.1-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 198 kB/s 
  Downloading fury-0.1.0-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 226 kB/s 
ERROR: Cannot install fury==0.1.0, fury==0.1.1, fury==0.1.2, fury==0.1.3, fury==0.1.4, fury==0.2.0, fury==0.3.0, fury==0.4.0, fury==0.5.0, fury==0.5.1, fury==0.6.0, fury==0.6.1 
and fury==0.7.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    fury 0.7.0 depends on vtk!=9.0.0 and >=8.1.2
    fury 0.6.1 depends on vtk!=9.0.0 and >=8.1.2
    fury 0.6.0 depends on vtk!=9.0.0 and >=8.1.2
    fury 0.5.1 depends on vtk>=8.1.0
    fury 0.5.0 depends on vtk>=8.1.0
    fury 0.4.0 depends on vtk>=8.1.0
    fury 0.3.0 depends on vtk>=8.1.0
    fury 0.2.0 depends on vtk>=8.1.0
    fury 0.1.4 depends on vtk>=8.1.0
    fury 0.1.3 depends on vtk>=8.1.0
    fury 0.1.2 depends on vtk>=8.1.0
    fury 0.1.1 depends on vtk>=8.1.0
    fury 0.1.0 depends on vtk>=8.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by Dhairya3124** [comment] 2021-03-20 12:24
Try using Anaconda Environment it might help.

**Comment by ganimtron-10** [comment] 2021-03-20 13:19
This is due to the dependencies issue as various versions of Fury require vtk library of different version greater than 8.0.1 and due to the bug in vtk 9.0.0 fury doesn't use this version so because of this incompatibility you are getting this issue.
I would recommended to install vtk library and fury separately. 
Use the below code to install vtk version greater than 9.0.0
```
pip install vtk>9.0.0
```
and then again install fury by clearing the cached fury files.

**Comment by Nibba2018** [comment] 2021-03-20 14:25
Hi @aryanxk02 , I cant seem to reproduce your issue. What OS and python version are you currently using?
You can also try to install fury from source using the following instructions [here](https://github.com/fury-gl/fury/blob/master/CONTRIBUTING.rst#get-started).

**Comment by skoudoro** [comment] 2021-03-20 16:16
> Installing fury from python 3.6.8 32-bit interpreter throws this error while installing fury.

Please, switch to a 64-bit python interpreter.  Many libraries will not work anymore on 32-bit, it is not only vtk...

**Comment by skoudoro** [comment] 2021-03-24 23:12
I am closing this issue, feel free to reopen it if you still have trouble

**Closed by skoudoro** 2021-03-24 23:12 UTC
Labels: type:Question

**Comment by aryanxk02** [comment] 2021-04-03 15:08
> As per My knowledge I think that this is due to the dependencies issue as various versions of Fury require vtk library of different version greater than 8.0.1 and due to the bug in vtk 9.0.0 fury doesn't use this version so because of this incompatibility you are getting this issue.
> Try to install vtk library and fury separately.
> Use the below code to install vtk version greater than 9.0.0
> 
> ```
> pip install vtk>9.0.0
> ```
> 
> and then again install fury by clearing the cached fury files.

`ERROR: Could not find a version that satisfies the requirement vtk`                                                    
`ERROR: No matching distribution found for vtk`

**Comment by aryanxk02** [comment] 2021-04-03 15:09
> Hi @aryanxk02 , I cant seem to reproduce your issue. What OS and python version are you currently using?
> You can also try to install fury from source using the following instructions [here](https://github.com/fury-gl/fury/blob/master/CONTRIBUTING.rst#get-started).

OS - Windows 64 bit
python ---version : Python 3.9.2

**Comment by aryanxk02** [comment] 2021-04-03 15:09
> > Installing fury from python 3.6.8 32-bit interpreter throws this error while installing fury.
> 
> Please, switch to a 64-bit python interpreter. Many libraries will not work anymore on 32-bit, it is not only vtk...

I am doing it on a 64 bit interpreter.

**Comment by aryanxk02** [comment] 2021-04-03 15:17
I think I should try with python 3.6.x 64 bit

**Comment by skoudoro** [comment] 2021-04-03 15:33
Hi @aryanxk02,

if you [look at Pypi here](https://pypi.org/project/vtk/#files), there is no wheel for python 3.9 yet. So you need to:
- use python 3.5, 3.6 3.7 or 3.8.
- avoid 32 bits as you can see on the link above
